development:
  adapter: sqlite3
  database: db/resumeonrails_develop.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/resumeonrails_test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: resumeonrails_production
  username: resumeonrails
  pool: 5
  timeout: 5000
